name: Build exercises
on: push
jobs:
  build-exercises:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
      - name: Creating file list
        id: files_list
        run: |
          cd exercises
          echo "::set-output name=files::$(printf '"exercises/%s" ' *.md)"
      - name: Removing old files
        run: |
          cd exercises
          rm exercises.pdf
      - name: Building pdf file
        uses: docker://pandoc/latex:2.9
        with:
          args: --output=exercises/exercises.pdf --pdf-engine=xelatex ${{ steps.files_list.outputs.files }}
      - name: Uploading pdf file
        uses: actions/upload-artifact@v3
        with:
          name: exercises
          path: exercises/exercises.pdf
      - name: Commiting changes
        uses: EndBug/add-and-commit@v9
        with:
          add: exercises/exercises.pdf
